Feature/contact info
PixieCoder/pixiesmc-generator pull request #12
Opened 2019-07-17 12:18 UTC by hehfg

Added the rest of contact info to footer and made the email in test a lighter blue to stick out from background.

2019-07-18 09:15 UTC, filiphazardous requested changes

2019-07-18 09:15 UTC, filiphazardous commented on templates/default/footer.tpl.html
> +            </div>
Fix indentation for above lines. Use standard format for street address (street name above city - and something to separate them). You seem to have forgotten to check what this looks like in a browser

2019-07-18 09:15 UTC, filiphazardous commented on templates/default/footer.tpl.html
> +    <a><%= phone %></a>
It's nice that you turn the phone number into a link. But please do it properly.

Check: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a

2019-07-19 11:09 UTC, hehfg commented
Made the changes you asked for.

2019-07-19 12:19 UTC, filiphazardous requested changes

2019-07-19 12:19 UTC, filiphazardous commented on templates/pcab/assets/css/pcab.css
> +.contactlink {
Separate words with a dash (-)

2019-07-19 12:19 UTC, filiphazardous commented on templates/pcab/assets/css/pcab.css
> +.contactInfo {
Separate words with a dash (-)

2019-07-19 12:22 UTC, filiphazardous requested changes

2019-07-19 12:22 UTC, filiphazardous commented on templates/default/footer.tpl.html
> +                <li><a href="tel:+<%= phone %>" class="contactlink"><%= phone %></a></li>
Remove the `+` sign - otherwise good

2019-07-19 14:32 UTC, filiphazardous approved these changes

2019-07-19 14:32 UTC, merged